spring:
  # MySQL‑douban‑mysql 13306
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/hr_agent_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: Admin@888888

  # Redis douban‑redis 宿主机16379
  # RabbitMQ douban‑rabbitmqAdmin@888888
#  rabbitmq:
#    host: 127.0.0.1
#    port: 15672
#    username: guest
#    password: guest
  # Redis douban‑redis 宿主机16379
  data:
    redis:
      host: 127.0.0.1
      port: 16379
      password: 123
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 4
          min-idle: 1
          max-wait: 2000ms

flowable:
  database-schema-update: true
  history-level: full
  async-executor-activate: false

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.example.hragent.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    root: INFO
    org.example.hragent: DEBUG
    com.baomidou.mybatisplus: WARN
    org.flowable: WARN
    org.apache.ibatis: WARN

# Elasticsearch7.17.9
#elasticsearch:
#  address: 127.0.0.1
#  port: 9200